debug: false
management.endpoints.web.exposure.include: "*"

logging:
    level:
        com.fastcampus.projectboard: debug
        org.springframework.web.servlet: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
    datasource:
        # mysql
        url: jdbc:mysql://localhost:3306/board
        username: jyuka
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

        # h2-db
#        url: jdbc:h2:mem:testdb
#        username: sa
#        driver-class-name: org.h2.Driver
    jpa:
        defer-datasource-initialization: true
        hibernate.ddl-auto: create
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.default_batch_fetch_size: 100
    h2.console.enabled: false
    sql.init.mode: always

    # Rest Repository 설정
    # 참고 url : https://supawer0728.github.io/2018/03/20/spring-data-rest/
    # https://docs.spring.io/spring-data/rest/docs/current/reference/html/
    data.rest:
        # http://127.0.0.1:8080/api 입력시 HAL Explorer
        base-path: /api
        # default: 모든 public repository. @RestResource의 exported가 false인 경우 제외
        # all: 가시성, annotation과 상관 없이 모든 repository 노출
        # annoation: exported가 true이며 @RepositoryRestResource, @RestResource가 달린 자원들을 노출
        # visibility: public interface만 노출
        detection-strategy: annotated

---
spring:
    config:
        activate:
            on-profile: testdb
#    datasource:
#        url: jdbc:h2:mem:board;mode=mysql
#        driver-class-name: org.h2.Driver
#    sql:
#        init:
#            mode: always
#
#    # 아레 조건에 대한 설정을 yml에서 관리
#    # @ActiveProfiles("testdb")
#    # @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
#    test.database.replace: none